enabled: true
sidebarEnabled: active
dropdown:
  enabled: true
contact:
  statement: 'Sed varius enim lorem ullamcorper dolore aliquam aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin sed aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.'
  email: new@zbmob.cz
  phone: '(555) 555-5555'
  street: '123 Any Street'
  city: AnyTown
  state: CA
  zip: '12345'
themeSlogan: ',  víc než oddíl'
